apiVersion: v1
kind: Service
metadata:
  name: dev-devpulse-service
spec:
  type: LoadBalancer  # This tells AWS to create a real Load Balancer
  selector:
    app: devpulse     # Ensure this matches the 'labels' in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80        # Access via standard web port
      targetPort: 8080 # The port your Java app runs on